### PR TITLE
Refixed parent function parameters overshadowing

### LINKED ISSUE #241: Terser overshadows parent function parameter while inlining function
**Bug report**

Terser overshadows parent function argument with 'undefined' (var declaration) if the names of arguments are the same. In output code we can see it tries to access properties of object `o` which has just been declared with `var`.

**Version (complete output of `terser -V`)**

npx: installed 5 in 1.585s
terser 3.14.1
undefined

**Complete CLI command or `minify()` options used**

`npx terser ./min.js -c -o res.js`

**`terser` input**

```JavaScript
var a = {};

(function(global) {
  function fail(o) {
    var result = {};

    function inner() {
      return outer({
        one: o.one,
        two: o.two
      });
    }

    result.inner = function() {
      return inner();
    };

    return result;
  }

  function outer(o) {
    var ret;

    if (o) {
      ret = o.one;
    } else {
      ret = o.two;
    }

    return ret;
  }

  global.fail = fail;
})(a);

var b = a.fail({});
b.inner();
```

**`terser` output or error**
Output:
```JavaScript
var a = {};
!(function(global) {
  a.fail = function(o) {
    var result = {};
    return (
      (result.inner = function() {
        return (o = { one: o.one, two: o.two }) ? o.one : o.two;
        var o;
      }),
      result
    );
  };
})();
var b = a.fail({});
b.inner();
```
Error:
```
TypeError: Cannot read property 'one' of undefined
    at Object.result.inner (/home/rafal/res.js:1:170)
    at Object.<anonymous> (/home/rafal/res.js:1:235)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```
**Expected result**

### LINKED ISSUE #285: Possibly wrong "instanceof" test?
https://github.com/terser-js/terser/blob/0cf9167c5278986744d6584255e153dd5555fd1a/lib/compress.js#L3992

So `this.parent_scope` first gets conveted to boolean and only then `instanceof` test takes place.

### PR DESCRIPTION
**Pull request by L2jLiga**
Closes #241
Closes #285

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
Great stuff, thanks! I'm really sorry but I moved lib/compress someplace else so there are conflicts that need fixing now :cry:

**Comment by L2jLiga** [comment]
@fabiosantoscode thx, rebased ;)

File: lib/compress/index.js [hunk 1]
```diff
@@ -3989,8 +3989,7 @@ merge(Compressor.prototype, {
     AST_Scope.DEFMETHOD("var_names", function varNames() {
         var var_names = this._var_names;
         if (!var_names) {
-            const isParentScopeAvailable = this.parent_scope && !this.parent_scope instanceof AST_Toplevel;
-            this._var_names = var_names = isParentScopeAvailable ? varNames.call(this.parent_scope) : Object.create(null);
+            this._var_names = var_names = this.parent_scope instanceof AST_Defun ? varNames.call(this.parent_scope) : Object.create(null);
```
Comment (fabiosantoscode) [inline lib/compress/index.js]: This would break with block scopes! You can't assume that the parent scope is going to be a function, it might be a `.block_scope` property of any AST_Block.

File: test/compress/block-scope.js [hunk 2]
```diff
@@ -229,30 +233,16 @@ issue_241: {
...
-            global.fail = fail;
-        })(a);
-
+                return result.inner = function () {
+                    return function (o) {
+                        return o ? o.one : o.two;
+                    }({one: o.one, two: o.two});
+                }, result;
+            };
+        }();
```
Comment (fabiosantoscode) [inline test/compress/block-scope.js]: I like this, it looks... _terser_ 

:sunglasses:

File: lib/compress/index.js (hunk 1 above)
Comment (L2jLiga) [reply lib/compress/index.js]: Will check and fix it later

Comment (L2jLiga) [reply lib/compress/index.js]: I tried to put function into [block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block) and it does not break anythink for me.. 😕 

**Command:**
`terser -c passes=3`

**Input:**
```javascript
var a = {};
var condition = false;

(function(global) {
    if (condition === true) {
        global.fail = function(o) {
            var result = {};

            function inner() {
                return outer({
                    one: 1,
                    two: o.two
                });
            }

            result.inner = function() {
                return inner();
            };

            return result;
        };
    } else {
        global.fail = function(o) {
            var result = {};

            function inner() {
                return outer({
                    one: o.one,
                    two: 2
                });
            }

            result.inner = function() {
                return inner();
            };

            return result;
        };
    }

    function outer(o) {
        console.log(o);
    }
})(a);

var b = a.fail({});
b.inner();
```

**Output:**
```javascript
var a={},condition=!1;!function(global){function outer(o){console.log(o)}a.fail=!0===condition?function(o){return{inner:function(){return outer({one:1,two:o.two})}}}:function(o){return{inner:function(){return outer({one:o.one,two:2})}}}}();var b=a.fail({});b.inner();
```

Comment (L2jLiga) [reply lib/compress/index.js]: Also checked with **input:**
```javascript
var a = {};
var condition = false;

(function (global) {
    function fail(o) {
        var result = {};

        if (condition)
            var inner = function () {
                return outer({
                    one: 1,
                    two: o.two
                });
            };
        else
            var inner = function () {
                return outer({
                    one: o.one,
                    two: 2
                });
            };

        result.inner = function () {
            return inner();
        };

        return result;
    };

    function outer(o) {
        console.log(o);
    }

    global.fail = fail;
})(a);

var b = a.fail({});
b.inner();
```

**output:**
```javascript
var a={},condition=!1;!function(global){function outer(o){console.log(o)}a.fail=function(o){var result={};if(condition)var inner=function(){return outer({one:1,two:o.two})};else inner=function(){return outer({one:o.one,two:2})};return result.inner=function(){return inner()},result}}();var b=a.fail({});b.inner();
```

Comment (fabiosantoscode) [reply lib/compress/index.js]: If the condition is set to `false` initially, it will get removed by the `conditionals` option.

Comment (fabiosantoscode) [reply lib/compress/index.js]: Because Terser knows you're just doing `false == true` and evaluates it to `false` and removes the if and therefore the block.

Comment (L2jLiga) [reply lib/compress/index.js]: Disagree, as I know, it will not get removed if I use var and will get removed if I use const

Comment (fabiosantoscode) [reply lib/compress/index.js]: Good point. I see that the condition was not removed, just turned into a tern.

I completely forgot that when I implemented block scopes, I used an AST_Scope instance as the AST_Block#block_scope property. That's why your code works. The parent scope is a block scope, but because of how this was implemented, it also happens to be an AST_Scope.

My confusion was because AST_Scope is the base class for functions too, so I thought this would only work if the parent scope was a function.

My apologies.

**Comment by fabiosantoscode** [comment]
LGTM. Would merge but there are outstanding conflicts right now.

**Comment by L2jLiga** [comment]
Rebased on master

**Comment by fabiosantoscode** [comment]
Thanks for this @L2jLiga, it's greatly appreciated!
